// This file is generated by `flutterfire configure`.
// Run: flutterfire configure --project=YOUR_PROJECT_ID
// to populate this file with your real Firebase config.
//
// Do NOT commit real API keys. Use environment-specific configs.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not configured.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Unsupported platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgOB8QE4Rgu0ZbnqE5hsco8N_XnUN8a3Q',
    appId: '1:168554410492:android:8248760f76e55f77340279',
    messagingSenderId: '168554410492',
    projectId: 'cdm26-33366',
    storageBucket: 'cdm26-33366.firebasestorage.app',
  );

  // Replace all placeholder values after running `flutterfire configure`

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjm9Tu_XIwHJ2go_vNRw_HUyOWTAjUXJM',
    appId: '1:168554410492:ios:8679def624653229340279',
    messagingSenderId: '168554410492',
    projectId: 'cdm26-33366',
    storageBucket: 'cdm26-33366.firebasestorage.app',
    iosBundleId: 'com.cdm26.cdm26',
  );

}