import * as admin from "firebase-admin";

// Run standalone: npx ts-node -e "require('./src/scripts/seed_wc2026')"
// Or call the exported seedWC2026 Cloud Function via HTTP.

const TOURNAMENT_ID = "wc_2026";

interface TeamDef {
  id: string;
  name: string;
  countryCode: string;
  flagEmoji: string;
  group: string;
}

interface PlayerDef {
  displayName: string;
  position: "gk" | "def" | "mid" | "fwd";
  fantasyPrice: number;
  shirtNumber?: number;
  age?: number;
}

const TEAMS: TeamDef[] = [
  { id: "arg", name: "Argentina",    countryCode: "AR", flagEmoji: "🇦🇷", group: "D" },
  { id: "bra", name: "Brazil",       countryCode: "BR", flagEmoji: "🇧🇷", group: "E" },
  { id: "fra", name: "France",       countryCode: "FR", flagEmoji: "🇫🇷", group: "G" },
  { id: "eng", name: "England",      countryCode: "GB", flagEmoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", group: "A" },
  { id: "esp", name: "Spain",        countryCode: "ES", flagEmoji: "🇪🇸", group: "B" },
  { id: "ger", name: "Germany",      countryCode: "DE", flagEmoji: "🇩🇪", group: "C" },
  { id: "por", name: "Portugal",     countryCode: "PT", flagEmoji: "🇵🇹", group: "H" },
  { id: "ned", name: "Netherlands",  countryCode: "NL", flagEmoji: "🇳🇱", group: "F" },
  { id: "usa", name: "USA",          countryCode: "US", flagEmoji: "🇺🇸", group: "A" },
  { id: "mex", name: "Mexico",       countryCode: "MX", flagEmoji: "🇲🇽", group: "B" },
  { id: "can", name: "Canada",       countryCode: "CA", flagEmoji: "🇨🇦", group: "C" },
  { id: "jpn", name: "Japan",        countryCode: "JP", flagEmoji: "🇯🇵", group: "L" },
  { id: "mar", name: "Morocco",      countryCode: "MA", flagEmoji: "🇲🇦", group: "I" },
  { id: "sen", name: "Senegal",      countryCode: "SN", flagEmoji: "🇸🇳", group: "H" },
  { id: "kor", name: "South Korea",  countryCode: "KR", flagEmoji: "🇰🇷", group: "J" },
  { id: "col", name: "Colombia",     countryCode: "CO", flagEmoji: "🇨🇴", group: "D" },
  { id: "uru", name: "Uruguay",      countryCode: "UY", flagEmoji: "🇺🇾", group: "E" },
  { id: "cro", name: "Croatia",      countryCode: "HR", flagEmoji: "🇭🇷", group: "G" },
  { id: "bel", name: "Belgium",      countryCode: "BE", flagEmoji: "🇧🇪", group: "I" },
  { id: "sui", name: "Switzerland",  countryCode: "CH", flagEmoji: "🇨🇭", group: "F" },
  { id: "aus", name: "Australia",    countryCode: "AU", flagEmoji: "🇦🇺", group: "L" },
  { id: "iri", name: "Iran",         countryCode: "IR", flagEmoji: "🇮🇷", group: "J" },
  { id: "ksa", name: "Saudi Arabia", countryCode: "SA", flagEmoji: "🇸🇦", group: "K" },
  { id: "ecu", name: "Ecuador",      countryCode: "EC", flagEmoji: "🇪🇨", group: "F" },
  { id: "gha", name: "Ghana",        countryCode: "GH", flagEmoji: "🇬🇭", group: "D" },
  { id: "nga", name: "Nigeria",      countryCode: "NG", flagEmoji: "🇳🇬", group: "B" },
  { id: "cmr", name: "Cameroon",     countryCode: "CM", flagEmoji: "🇨🇲", group: "G" },
  { id: "egy", name: "Egypt",        countryCode: "EG", flagEmoji: "🇪🇬", group: "K" },
  { id: "tur", name: "Turkey",       countryCode: "TR", flagEmoji: "🇹🇷", group: "I" },
  { id: "pol", name: "Poland",       countryCode: "PL", flagEmoji: "🇵🇱", group: "J" },
  { id: "aut", name: "Austria",      countryCode: "AT", flagEmoji: "🇦🇹", group: "K" },
  { id: "srb", name: "Serbia",       countryCode: "RS", flagEmoji: "🇷🇸", group: "C" },
];

const PLAYERS: Record<string, PlayerDef[]> = {
  arg: [
    { displayName: "E. Martínez",    position: "gk",  fantasyPrice: 15, shirtNumber: 23, age: 32 },
    { displayName: "F. Armani",      position: "gk",  fantasyPrice: 4,  shirtNumber: 1,  age: 38 },
    { displayName: "N. Otamendi",    position: "def", fantasyPrice: 6,  shirtNumber: 19, age: 36 },
    { displayName: "L. Martínez",    position: "def", fantasyPrice: 13, shirtNumber: 5,  age: 27 },
    { displayName: "N. Molina",      position: "def", fantasyPrice: 9,  shirtNumber: 26, age: 27 },
    { displayName: "M. Acuña",       position: "def", fantasyPrice: 6,  shirtNumber: 8,  age: 33 },
    { displayName: "G. Pezzella",    position: "def", fantasyPrice: 4,  shirtNumber: 6,  age: 33 },
    { displayName: "L. Messi",       position: "mid", fantasyPrice: 25, shirtNumber: 10, age: 38 },
    { displayName: "R. De Paul",     position: "mid", fantasyPrice: 9,  shirtNumber: 7,  age: 31 },
    { displayName: "A. Mac Allister",position: "mid", fantasyPrice: 12, shirtNumber: 20, age: 26 },
    { displayName: "E. Fernández",   position: "mid", fantasyPrice: 13, shirtNumber: 24, age: 24 },
    { displayName: "L. Paredes",     position: "mid", fantasyPrice: 5,  shirtNumber: 5,  age: 31 },
    { displayName: "Lautaro Martínez",position:"fwd", fantasyPrice: 20, shirtNumber: 22, age: 27 },
    { displayName: "J. Álvarez",     position: "fwd", fantasyPrice: 17, shirtNumber: 9,  age: 25 },
    { displayName: "P. Dybala",      position: "fwd", fantasyPrice: 9,  shirtNumber: 21, age: 31 },
  ],
  bra: [
    { displayName: "Alisson",        position: "gk",  fantasyPrice: 13, shirtNumber: 1,  age: 32 },
    { displayName: "Ederson",        position: "gk",  fantasyPrice: 11, shirtNumber: 23, age: 31 },
    { displayName: "Marquinhos",     position: "def", fantasyPrice: 11, shirtNumber: 4,  age: 31 },
    { displayName: "É. Militão",     position: "def", fantasyPrice: 13, shirtNumber: 3,  age: 27 },
    { displayName: "Danilo",         position: "def", fantasyPrice: 6,  shirtNumber: 2,  age: 34 },
    { displayName: "A. Sandro",      position: "def", fantasyPrice: 4,  shirtNumber: 6,  age: 34 },
    { displayName: "R. Lodi",        position: "def", fantasyPrice: 6,  shirtNumber: 12, age: 27 },
    { displayName: "Casemiro",       position: "mid", fantasyPrice: 9,  shirtNumber: 5,  age: 33 },
    { displayName: "B. Guimarães",   position: "mid", fantasyPrice: 17, shirtNumber: 8,  age: 27 },
    { displayName: "L. Paquetá",     position: "mid", fantasyPrice: 13, shirtNumber: 10, age: 27 },
    { displayName: "Vinicius Jr",    position: "fwd", fantasyPrice: 24, shirtNumber: 7,  age: 24 },
    { displayName: "Rodrygo",        position: "fwd", fantasyPrice: 17, shirtNumber: 11, age: 24 },
    { displayName: "G. Martinelli",  position: "fwd", fantasyPrice: 13, shirtNumber: 14, age: 24 },
    { displayName: "Richarlison",    position: "fwd", fantasyPrice: 9,  shirtNumber: 9,  age: 28 },
    { displayName: "Raphinha",       position: "fwd", fantasyPrice: 13, shirtNumber: 19, age: 28 },
  ],
  fra: [
    { displayName: "M. Maignan",     position: "gk",  fantasyPrice: 13, shirtNumber: 16, age: 29 },
    { displayName: "A. Areola",      position: "gk",  fantasyPrice: 6,  shirtNumber: 23, age: 32 },
    { displayName: "T. Hernandez",   position: "def", fantasyPrice: 13, shirtNumber: 22, age: 27 },
    { displayName: "D. Upamecano",   position: "def", fantasyPrice: 11, shirtNumber: 4,  age: 26 },
    { displayName: "W. Saliba",      position: "def", fantasyPrice: 17, shirtNumber: 17, age: 24 },
    { displayName: "B. Pavard",      position: "def", fantasyPrice: 9,  shirtNumber: 5,  age: 29 },
    { displayName: "J. Koundé",      position: "def", fantasyPrice: 13, shirtNumber: 2,  age: 26 },
    { displayName: "A. Griezmann",   position: "mid", fantasyPrice: 13, shirtNumber: 7,  age: 34 },
    { displayName: "E. Camavinga",   position: "mid", fantasyPrice: 13, shirtNumber: 8,  age: 22 },
    { displayName: "A. Tchouaméni",  position: "mid", fantasyPrice: 17, shirtNumber: 8,  age: 25 },
    { displayName: "A. Rabiot",      position: "mid", fantasyPrice: 9,  shirtNumber: 14, age: 30 },
    { displayName: "K. Mbappé",      position: "fwd", fantasyPrice: 25, shirtNumber: 10, age: 26 },
    { displayName: "O. Dembélé",     position: "fwd", fantasyPrice: 13, shirtNumber: 11, age: 28 },
    { displayName: "M. Thuram",      position: "fwd", fantasyPrice: 13, shirtNumber: 9,  age: 27 },
    { displayName: "R. Barcola",     position: "fwd", fantasyPrice: 9,  shirtNumber: 18, age: 22 },
  ],
  eng: [
    { displayName: "J. Pickford",    position: "gk",  fantasyPrice: 11, shirtNumber: 1,  age: 31 },
    { displayName: "N. Pope",        position: "gk",  fantasyPrice: 9,  shirtNumber: 22, age: 33 },
    { displayName: "K. Walker",      position: "def", fantasyPrice: 6,  shirtNumber: 2,  age: 35 },
    { displayName: "H. Maguire",     position: "def", fantasyPrice: 6,  shirtNumber: 6,  age: 32 },
    { displayName: "J. Stones",      position: "def", fantasyPrice: 9,  shirtNumber: 5,  age: 31 },
    { displayName: "B. Chilwell",    position: "def", fantasyPrice: 9,  shirtNumber: 21, age: 28 },
    { displayName: "T. Alexander-Arnold",position:"def",fantasyPrice:13, shirtNumber: 66, age: 26 },
    { displayName: "J. Bellingham",  position: "mid", fantasyPrice: 25, shirtNumber: 10, age: 21 },
    { displayName: "D. Rice",        position: "mid", fantasyPrice: 17, shirtNumber: 4,  age: 26 },
    { displayName: "B. Saka",        position: "mid", fantasyPrice: 20, shirtNumber: 17, age: 23 },
    { displayName: "P. Foden",       position: "mid", fantasyPrice: 20, shirtNumber: 7,  age: 25 },
    { displayName: "H. Kane",        position: "fwd", fantasyPrice: 22, shirtNumber: 9,  age: 32 },
    { displayName: "M. Rashford",    position: "fwd", fantasyPrice: 13, shirtNumber: 11, age: 27 },
    { displayName: "C. Palmer",      position: "fwd", fantasyPrice: 17, shirtNumber: 25, age: 23 },
    { displayName: "A. Gordon",      position: "fwd", fantasyPrice: 11, shirtNumber: 14, age: 24 },
  ],
  esp: [
    { displayName: "U. Simón",       position: "gk",  fantasyPrice: 11, shirtNumber: 1,  age: 27 },
    { displayName: "D. Raya",        position: "gk",  fantasyPrice: 9,  shirtNumber: 13, age: 29 },
    { displayName: "D. Carvajal",    position: "def", fantasyPrice: 9,  shirtNumber: 2,  age: 32 },
    { displayName: "P. Torres",      position: "def", fantasyPrice: 11, shirtNumber: 14, age: 28 },
    { displayName: "A. Laporte",     position: "def", fantasyPrice: 9,  shirtNumber: 4,  age: 31 },
    { displayName: "R. Le Normand",  position: "def", fantasyPrice: 9,  shirtNumber: 24, age: 27 },
    { displayName: "M. Cucurella",   position: "def", fantasyPrice: 9,  shirtNumber: 15, age: 26 },
    { displayName: "Pedri",          position: "mid", fantasyPrice: 22, shirtNumber: 26, age: 23 },
    { displayName: "Rodri",          position: "mid", fantasyPrice: 22, shirtNumber: 16, age: 28 },
    { displayName: "Gavi",           position: "mid", fantasyPrice: 20, shirtNumber: 9,  age: 20 },
    { displayName: "F. Ruiz",        position: "mid", fantasyPrice: 13, shirtNumber: 8,  age: 28 },
    { displayName: "D. Olmo",        position: "fwd", fantasyPrice: 17, shirtNumber: 10, age: 27 },
    { displayName: "Á. Morata",      position: "fwd", fantasyPrice: 11, shirtNumber: 7,  age: 32 },
    { displayName: "F. Torres",      position: "fwd", fantasyPrice: 9,  shirtNumber: 11, age: 24 },
    { displayName: "N. Williams",    position: "fwd", fantasyPrice: 17, shirtNumber: 17, age: 22 },
  ],
  ger: [
    { displayName: "M. Neuer",       position: "gk",  fantasyPrice: 7,  shirtNumber: 1,  age: 39 },
    { displayName: "M. ter Stegen",  position: "gk",  fantasyPrice: 9,  shirtNumber: 22, age: 33 },
    { displayName: "A. Rüdiger",     position: "def", fantasyPrice: 9,  shirtNumber: 2,  age: 32 },
    { displayName: "N. Schlotterbeck",position:"def", fantasyPrice: 11, shirtNumber: 5,  age: 25 },
    { displayName: "J. Kimmich",     position: "def", fantasyPrice: 17, shirtNumber: 6,  age: 30 },
    { displayName: "D. Raum",        position: "def", fantasyPrice: 9,  shirtNumber: 19, age: 27 },
    { displayName: "N. Süle",        position: "def", fantasyPrice: 7,  shirtNumber: 15, age: 29 },
    { displayName: "I. Gündoğan",    position: "mid", fantasyPrice: 9,  shirtNumber: 21, age: 34 },
    { displayName: "L. Goretzka",    position: "mid", fantasyPrice: 9,  shirtNumber: 8,  age: 30 },
    { displayName: "L. Sané",        position: "mid", fantasyPrice: 11, shirtNumber: 10, age: 29 },
    { displayName: "F. Wirtz",       position: "mid", fantasyPrice: 22, shirtNumber: 10, age: 22 },
    { displayName: "K. Havertz",     position: "fwd", fantasyPrice: 13, shirtNumber: 7,  age: 26 },
    { displayName: "S. Gnabry",      position: "fwd", fantasyPrice: 9,  shirtNumber: 20, age: 29 },
    { displayName: "N. Füllkrug",    position: "fwd", fantasyPrice: 11, shirtNumber: 9,  age: 32 },
    { displayName: "J. Musiala",     position: "fwd", fantasyPrice: 20, shirtNumber: 14, age: 22 },
  ],
  por: [
    { displayName: "D. Costa",       position: "gk",  fantasyPrice: 13, shirtNumber: 1,  age: 25 },
    { displayName: "R. Patrício",    position: "gk",  fantasyPrice: 6,  shirtNumber: 12, age: 37 },
    { displayName: "R. Dias",        position: "def", fantasyPrice: 17, shirtNumber: 4,  age: 27 },
    { displayName: "Pepe",           position: "def", fantasyPrice: 4,  shirtNumber: 3,  age: 42 },
    { displayName: "N. Mendes",      position: "def", fantasyPrice: 13, shirtNumber: 19, age: 23 },
    { displayName: "D. Dalot",       position: "def", fantasyPrice: 9,  shirtNumber: 20, age: 25 },
    { displayName: "J. Cancelo",     position: "def", fantasyPrice: 11, shirtNumber: 5,  age: 30 },
    { displayName: "C. Ronaldo",     position: "mid", fantasyPrice: 11, shirtNumber: 7,  age: 41 },
    { displayName: "B. Silva",       position: "mid", fantasyPrice: 20, shirtNumber: 10, age: 30 },
    { displayName: "B. Fernandes",   position: "mid", fantasyPrice: 17, shirtNumber: 8,  age: 30 },
    { displayName: "Vitinha",        position: "mid", fantasyPrice: 13, shirtNumber: 16, age: 25 },
    { displayName: "R. Leão",        position: "fwd", fantasyPrice: 17, shirtNumber: 11, age: 25 },
    { displayName: "G. Ramos",       position: "fwd", fantasyPrice: 13, shirtNumber: 9,  age: 23 },
    { displayName: "P. Neto",        position: "fwd", fantasyPrice: 11, shirtNumber: 21, age: 24 },
    { displayName: "J. Félix",       position: "fwd", fantasyPrice: 13, shirtNumber: 11, age: 25 },
  ],
  ned: [
    { displayName: "B. Verbruggen",  position: "gk",  fantasyPrice: 11, shirtNumber: 1,  age: 22 },
    { displayName: "R. Pasveer",     position: "gk",  fantasyPrice: 5,  shirtNumber: 23, age: 36 },
    { displayName: "V. van Dijk",    position: "def", fantasyPrice: 13, shirtNumber: 4,  age: 33 },
    { displayName: "M. de Ligt",     position: "def", fantasyPrice: 11, shirtNumber: 3,  age: 25 },
    { displayName: "D. Dumfries",    position: "def", fantasyPrice: 9,  shirtNumber: 22, age: 28 },
    { displayName: "N. Aké",         position: "def", fantasyPrice: 9,  shirtNumber: 5,  age: 30 },
    { displayName: "S. de Vrij",     position: "def", fantasyPrice: 6,  shirtNumber: 6,  age: 33 },
    { displayName: "F. de Jong",     position: "mid", fantasyPrice: 17, shirtNumber: 21, age: 27 },
    { displayName: "X. Simons",      position: "mid", fantasyPrice: 20, shirtNumber: 10, age: 22 },
    { displayName: "T. Reijnders",   position: "mid", fantasyPrice: 13, shirtNumber: 8,  age: 26 },
    { displayName: "C. Gakpo",       position: "fwd", fantasyPrice: 17, shirtNumber: 11, age: 25 },
    { displayName: "M. Depay",       position: "fwd", fantasyPrice: 9,  shirtNumber: 9,  age: 31 },
    { displayName: "W. Weghorst",    position: "fwd", fantasyPrice: 6,  shirtNumber: 19, age: 32 },
    { displayName: "D. Malen",       position: "fwd", fantasyPrice: 11, shirtNumber: 7,  age: 26 },
    { displayName: "B. Brobbey",     position: "fwd", fantasyPrice: 9,  shirtNumber: 9,  age: 23 },
  ],
  usa: [
    { displayName: "M. Turner",      position: "gk",  fantasyPrice: 7,  shirtNumber: 1,  age: 31 },
    { displayName: "Z. Steffen",     position: "gk",  fantasyPrice: 5,  shirtNumber: 12, age: 30 },
    { displayName: "S. Dest",        position: "def", fantasyPrice: 9,  shirtNumber: 2,  age: 24 },
    { displayName: "M. McKenzie",    position: "def", fantasyPrice: 6,  shirtNumber: 4,  age: 26 },
    { displayName: "T. Ream",        position: "def", fantasyPrice: 4,  shirtNumber: 5,  age: 37 },
    { displayName: "J. Scally",      position: "def", fantasyPrice: 6,  shirtNumber: 19, age: 22 },
    { displayName: "A. Robinson",    position: "def", fantasyPrice: 9,  shirtNumber: 14, age: 28 },
    { displayName: "C. Pulisic",     position: "mid", fantasyPrice: 17, shirtNumber: 10, age: 26 },
    { displayName: "T. Adams",       position: "mid", fantasyPrice: 11, shirtNumber: 4,  age: 26 },
    { displayName: "W. McKennie",    position: "mid", fantasyPrice: 9,  shirtNumber: 8,  age: 26 },
    { displayName: "Y. Musah",       position: "mid", fantasyPrice: 11, shirtNumber: 6,  age: 22 },
    { displayName: "F. Balogun",     position: "fwd", fantasyPrice: 13, shirtNumber: 9,  age: 24 },
    { displayName: "J. Sargent",     position: "fwd", fantasyPrice: 9,  shirtNumber: 11, age: 25 },
    { displayName: "B. Aaronson",    position: "fwd", fantasyPrice: 9,  shirtNumber: 11, age: 24 },
    { displayName: "G. Reyna",       position: "fwd", fantasyPrice: 9,  shirtNumber: 7,  age: 22 },
  ],
  mex: [
    { displayName: "G. Ochoa",       position: "gk",  fantasyPrice: 5,  shirtNumber: 1,  age: 39 },
    { displayName: "L. Malagón",     position: "gk",  fantasyPrice: 7,  shirtNumber: 13, age: 26 },
    { displayName: "N. Araujo",      position: "def", fantasyPrice: 5,  shirtNumber: 3,  age: 30 },
    { displayName: "C. Montes",      position: "def", fantasyPrice: 6,  shirtNumber: 15, age: 27 },
    { displayName: "J. Sánchez",     position: "def", fantasyPrice: 6,  shirtNumber: 21, age: 25 },
    { displayName: "L. Rodríguez",   position: "def", fantasyPrice: 5,  shirtNumber: 19, age: 33 },
    { displayName: "K. Álvarez",     position: "def", fantasyPrice: 6,  shirtNumber: 25, age: 24 },
    { displayName: "H. Lozano",      position: "mid", fantasyPrice: 9,  shirtNumber: 22, age: 29 },
    { displayName: "H. Herrera",     position: "mid", fantasyPrice: 5,  shirtNumber: 16, age: 35 },
    { displayName: "R. Alvarado",    position: "mid", fantasyPrice: 6,  shirtNumber: 18, age: 26 },
    { displayName: "O. Pineda",      position: "mid", fantasyPrice: 6,  shirtNumber: 10, age: 29 },
    { displayName: "R. Jiménez",     position: "fwd", fantasyPrice: 9,  shirtNumber: 9,  age: 33 },
    { displayName: "S. Giménez",     position: "fwd", fantasyPrice: 13, shirtNumber: 11, age: 23 },
    { displayName: "H. Martín",      position: "fwd", fantasyPrice: 5,  shirtNumber: 14, age: 30 },
    { displayName: "A. Vega",        position: "fwd", fantasyPrice: 6,  shirtNumber: 17, age: 24 },
  ],
  can: [
    { displayName: "M. Borjan",      position: "gk",  fantasyPrice: 5,  shirtNumber: 18, age: 36 },
    { displayName: "M. Crépeau",     position: "gk",  fantasyPrice: 6,  shirtNumber: 1,  age: 30 },
    { displayName: "A. Johnston",    position: "def", fantasyPrice: 7,  shirtNumber: 2,  age: 26 },
    { displayName: "K. Miller",      position: "def", fantasyPrice: 6,  shirtNumber: 5,  age: 28 },
    { displayName: "D. Henry",       position: "def", fantasyPrice: 4,  shirtNumber: 13, age: 34 },
    { displayName: "S. Adekugbe",    position: "def", fantasyPrice: 5,  shirtNumber: 11, age: 29 },
    { displayName: "D. Cornelius",   position: "def", fantasyPrice: 4,  shirtNumber: 3,  age: 31 },
    { displayName: "A. Davies",      position: "mid", fantasyPrice: 22, shirtNumber: 3,  age: 24 },
    { displayName: "T. Buchanan",    position: "mid", fantasyPrice: 9,  shirtNumber: 11, age: 25 },
    { displayName: "S. Eustáquio",   position: "mid", fantasyPrice: 9,  shirtNumber: 7,  age: 27 },
    { displayName: "M. Larin",       position: "mid", fantasyPrice: 6,  shirtNumber: 9,  age: 30 },
    { displayName: "J. David",       position: "fwd", fantasyPrice: 17, shirtNumber: 9,  age: 25 },
    { displayName: "K. Cavallini",   position: "fwd", fantasyPrice: 5,  shirtNumber: 7,  age: 33 },
    { displayName: "L. Laryea",      position: "fwd", fantasyPrice: 6,  shirtNumber: 8,  age: 28 },
    { displayName: "C. Larin",       position: "fwd", fantasyPrice: 7,  shirtNumber: 17, age: 29 },
  ],
  jpn: [
    { displayName: "S. Gonda",       position: "gk",  fantasyPrice: 6,  shirtNumber: 12, age: 35 },
    { displayName: "Z. Suzuki",      position: "gk",  fantasyPrice: 5,  shirtNumber: 1,  age: 23 },
    { displayName: "M. Yoshida",     position: "def", fantasyPrice: 4,  shirtNumber: 22, age: 36 },
    { displayName: "K. Itakura",     position: "def", fantasyPrice: 6,  shirtNumber: 3,  age: 27 },
    { displayName: "H. Ito",         position: "def", fantasyPrice: 9,  shirtNumber: 5,  age: 25 },
    { displayName: "Y. Nagatomo",    position: "def", fantasyPrice: 3,  shirtNumber: 7,  age: 38 },
    { displayName: "M. Yamane",      position: "def", fantasyPrice: 6,  shirtNumber: 2,  age: 28 },
    { displayName: "W. Endo",        position: "mid", fantasyPrice: 9,  shirtNumber: 6,  age: 32 },
    { displayName: "T. Kubo",        position: "mid", fantasyPrice: 20, shirtNumber: 14, age: 23 },
    { displayName: "J. Ito",         position: "mid", fantasyPrice: 9,  shirtNumber: 17, age: 31 },
    { displayName: "D. Kamada",      position: "mid", fantasyPrice: 9,  shirtNumber: 10, age: 28 },
    { displayName: "K. Mitoma",      position: "fwd", fantasyPrice: 17, shirtNumber: 11, age: 27 },
    { displayName: "A. Ueda",        position: "fwd", fantasyPrice: 9,  shirtNumber: 13, age: 26 },
    { displayName: "A. Tanaka",      position: "fwd", fantasyPrice: 9,  shirtNumber: 8,  age: 26 },
    { displayName: "T. Minamino",    position: "fwd", fantasyPrice: 9,  shirtNumber: 9,  age: 30 },
  ],
  mar: [
    { displayName: "Y. Bounou",      position: "gk",  fantasyPrice: 11, shirtNumber: 1,  age: 33 },
    { displayName: "M. Mohamedi",    position: "gk",  fantasyPrice: 4,  shirtNumber: 16, age: 35 },
    { displayName: "A. Hakimi",      position: "def", fantasyPrice: 22, shirtNumber: 2,  age: 26 },
    { displayName: "J. El Yamiq",    position: "def", fantasyPrice: 6,  shirtNumber: 6,  age: 32 },
    { displayName: "R. Saïss",       position: "def", fantasyPrice: 5,  shirtNumber: 16, age: 34 },
    { displayName: "N. Mazraoui",    position: "def", fantasyPrice: 9,  shirtNumber: 3,  age: 27 },
    { displayName: "A. Dari",        position: "def", fantasyPrice: 7,  shirtNumber: 5,  age: 26 },
    { displayName: "S. Amrabat",     position: "mid", fantasyPrice: 11, shirtNumber: 4,  age: 28 },
    { displayName: "A. Ounahi",      position: "mid", fantasyPrice: 9,  shirtNumber: 8,  age: 24 },
    { displayName: "H. Ziyech",      position: "mid", fantasyPrice: 9,  shirtNumber: 7,  age: 32 },
    { displayName: "S. Amallah",     position: "mid", fantasyPrice: 6,  shirtNumber: 17, age: 27 },
    { displayName: "Y. En-Nesyri",   position: "fwd", fantasyPrice: 13, shirtNumber: 19, age: 27 },
    { displayName: "S. Boufal",      position: "fwd", fantasyPrice: 7,  shirtNumber: 11, age: 31 },
    { displayName: "A. Ezzalzouli",  position: "fwd", fantasyPrice: 9,  shirtNumber: 18, age: 23 },
    { displayName: "R. El Kaabi",    position: "fwd", fantasyPrice: 9,  shirtNumber: 9,  age: 27 },
  ],
  sen: [
    { displayName: "É. Mendy",       position: "gk",  fantasyPrice: 9,  shirtNumber: 1,  age: 32 },
    { displayName: "A. Gomis",       position: "gk",  fantasyPrice: 6,  shirtNumber: 16, age: 31 },
    { displayName: "K. Koulibaly",   position: "def", fantasyPrice: 11, shirtNumber: 3,  age: 33 },
    { displayName: "A. Diallo",      position: "def", fantasyPrice: 7,  shirtNumber: 5,  age: 28 },
    { displayName: "I. Jakobs",      position: "def", fantasyPrice: 6,  shirtNumber: 18, age: 25 },
    { displayName: "F. Mendy",       position: "def", fantasyPrice: 5,  shirtNumber: 14, age: 28 },
    { displayName: "P. Cissé",       position: "def", fantasyPrice: 5,  shirtNumber: 15, age: 28 },
    { displayName: "I. Gueye",       position: "mid", fantasyPrice: 7,  shirtNumber: 17, age: 35 },
    { displayName: "P. Sarr",        position: "mid", fantasyPrice: 11, shirtNumber: 8,  age: 22 },
    { displayName: "C. Kouyaté",     position: "mid", fantasyPrice: 5,  shirtNumber: 13, age: 35 },
    { displayName: "L. Diouf",       position: "mid", fantasyPrice: 6,  shirtNumber: 11, age: 25 },
    { displayName: "S. Mané",        position: "fwd", fantasyPrice: 11, shirtNumber: 10, age: 34 },
    { displayName: "I. Sarr",        position: "fwd", fantasyPrice: 9,  shirtNumber: 23, age: 27 },
    { displayName: "B. Dia",         position: "fwd", fantasyPrice: 9,  shirtNumber: 9,  age: 27 },
    { displayName: "N. Diedhiou",    position: "fwd", fantasyPrice: 6,  shirtNumber: 19, age: 26 },
  ],
  kor: [
    { displayName: "Jo Hyeon-woo",   position: "gk",  fantasyPrice: 5,  shirtNumber: 21, age: 33 },
    { displayName: "K. Seung-gyu",   position: "gk",  fantasyPrice: 4,  shirtNumber: 1,  age: 36 },
    { displayName: "Kim Min-jae",     position: "def", fantasyPrice: 20, shirtNumber: 3,  age: 28 },
    { displayName: "Kim Jin-su",      position: "def", fantasyPrice: 5,  shirtNumber: 15, age: 31 },
    { displayName: "Kim Young-gwon",  position: "def", fantasyPrice: 4,  shirtNumber: 19, age: 35 },
    { displayName: "K. Moon-hwan",   position: "def", fantasyPrice: 5,  shirtNumber: 13, age: 30 },
    { displayName: "S. Young-woo",   position: "def", fantasyPrice: 4,  shirtNumber: 17, age: 25 },
    { displayName: "Son Heung-min",   position: "mid", fantasyPrice: 22, shirtNumber: 7,  age: 33 },
    { displayName: "Lee Kang-in",     position: "mid", fantasyPrice: 17, shirtNumber: 10, age: 24 },
    { displayName: "H. In-beom",      position: "mid", fantasyPrice: 7,  shirtNumber: 8,  age: 29 },
    { displayName: "J. Woo-young",    position: "mid", fantasyPrice: 5,  shirtNumber: 4,  age: 32 },
    { displayName: "H. Hee-chan",      position: "fwd", fantasyPrice: 11, shirtNumber: 11, age: 28 },
    { displayName: "C. Gue-sung",     position: "fwd", fantasyPrice: 9,  shirtNumber: 9,  age: 26 },
    { displayName: "Oh Hyeon-gyu",    position: "fwd", fantasyPrice: 7,  shirtNumber: 18, age: 23 },
    { displayName: "B. Seung-ho",     position: "fwd", fantasyPrice: 5,  shirtNumber: 16, age: 27 },
  ],
  col: [
    { displayName: "C. Vargas",      position: "gk",  fantasyPrice: 6,  shirtNumber: 1,  age: 33 },
    { displayName: "D. Ospina",      position: "gk",  fantasyPrice: 5,  shirtNumber: 12, age: 36 },
    { displayName: "D. Sánchez",     position: "def", fantasyPrice: 9,  shirtNumber: 6,  age: 28 },
    { displayName: "Y. Mina",        position: "def", fantasyPrice: 6,  shirtNumber: 13, age: 30 },
    { displayName: "D. Muñoz",       position: "def", fantasyPrice: 9,  shirtNumber: 2,  age: 27 },
    { displayName: "J. Mojica",      position: "def", fantasyPrice: 6,  shirtNumber: 3,  age: 30 },
    { displayName: "C. Cuesta",      position: "def", fantasyPrice: 7,  shirtNumber: 4,  age: 26 },
    { displayName: "J. Rodríguez",   position: "mid", fantasyPrice: 9,  shirtNumber: 10, age: 33 },
    { displayName: "L. Díaz",        position: "mid", fantasyPrice: 20, shirtNumber: 7,  age: 27 },
    { displayName: "M. Uribe",       position: "mid", fantasyPrice: 7,  shirtNumber: 8,  age: 31 },
    { displayName: "R. Ríos",        position: "mid", fantasyPrice: 9,  shirtNumber: 15, age: 24 },
    { displayName: "C. Hernández",   position: "fwd", fantasyPrice: 9,  shirtNumber: 9,  age: 26 },
    { displayName: "R. Falcao",      position: "fwd", fantasyPrice: 4,  shirtNumber: 9,  age: 39 },
    { displayName: "M. Borja",       position: "fwd", fantasyPrice: 7,  shirtNumber: 19, age: 31 },
    { displayName: "J. Córdoba",     position: "fwd", fantasyPrice: 7,  shirtNumber: 11, age: 31 },
  ],
  uru: [
    { displayName: "S. Rochet",      position: "gk",  fantasyPrice: 7,  shirtNumber: 1,  age: 29 },
    { displayName: "F. Muslera",     position: "gk",  fantasyPrice: 4,  shirtNumber: 12, age: 38 },
    { displayName: "J. Giménez",     position: "def", fantasyPrice: 11, shirtNumber: 2,  age: 30 },
    { displayName: "R. Araújo",      position: "def", fantasyPrice: 20, shirtNumber: 4,  age: 26 },
    { displayName: "S. Coates",      position: "def", fantasyPrice: 6,  shirtNumber: 3,  age: 34 },
    { displayName: "M. Olivera",     position: "def", fantasyPrice: 9,  shirtNumber: 15, age: 27 },
    { displayName: "N. Nández",      position: "def", fantasyPrice: 7,  shirtNumber: 16, age: 29 },
    { displayName: "F. Valverde",    position: "mid", fantasyPrice: 24, shirtNumber: 14, age: 26 },
    { displayName: "R. Bentancur",   position: "mid", fantasyPrice: 11, shirtNumber: 8,  age: 27 },
    { displayName: "M. Vecino",      position: "mid", fantasyPrice: 5,  shirtNumber: 15, age: 33 },
    { displayName: "F. Pellistri",   position: "mid", fantasyPrice: 7,  shirtNumber: 22, age: 24 },
    { displayName: "D. Núñez",       position: "fwd", fantasyPrice: 20, shirtNumber: 11, age: 25 },
    { displayName: "M. Gómez",       position: "fwd", fantasyPrice: 6,  shirtNumber: 9,  age: 28 },
    { displayName: "F. Torres",      position: "fwd", fantasyPrice: 7,  shirtNumber: 17, age: 24 },
    { displayName: "L. Suárez",      position: "fwd", fantasyPrice: 5,  shirtNumber: 9,  age: 38 },
  ],
  cro: [
    { displayName: "D. Livaković",   position: "gk",  fantasyPrice: 11, shirtNumber: 1,  age: 29 },
    { displayName: "I. Ivušić",      position: "gk",  fantasyPrice: 5,  shirtNumber: 23, age: 28 },
    { displayName: "J. Gvardiol",    position: "def", fantasyPrice: 22, shirtNumber: 3,  age: 23 },
    { displayName: "J. Šutalo",      position: "def", fantasyPrice: 11, shirtNumber: 5,  age: 23 },
    { displayName: "D. Lovren",      position: "def", fantasyPrice: 4,  shirtNumber: 6,  age: 36 },
    { displayName: "B. Sosa",        position: "def", fantasyPrice: 7,  shirtNumber: 11, age: 27 },
    { displayName: "J. Juranović",   position: "def", fantasyPrice: 9,  shirtNumber: 2,  age: 29 },
    { displayName: "L. Modrić",      position: "mid", fantasyPrice: 9,  shirtNumber: 10, age: 40 },
    { displayName: "M. Kovačić",     position: "mid", fantasyPrice: 11, shirtNumber: 8,  age: 31 },
    { displayName: "M. Brozović",    position: "mid", fantasyPrice: 9,  shirtNumber: 11, age: 32 },
    { displayName: "L. Majer",       position: "mid", fantasyPrice: 11, shirtNumber: 7,  age: 27 },
    { displayName: "A. Kramarić",    position: "fwd", fantasyPrice: 11, shirtNumber: 9,  age: 34 },
    { displayName: "I. Perišić",     position: "fwd", fantasyPrice: 7,  shirtNumber: 4,  age: 36 },
    { displayName: "B. Petković",    position: "fwd", fantasyPrice: 6,  shirtNumber: 16, age: 30 },
    { displayName: "A. Budimir",     position: "fwd", fantasyPrice: 5,  shirtNumber: 19, age: 34 },
  ],
  bel: [
    { displayName: "T. Courtois",    position: "gk",  fantasyPrice: 17, shirtNumber: 1,  age: 33 },
    { displayName: "K. Casteels",    position: "gk",  fantasyPrice: 9,  shirtNumber: 23, age: 32 },
    { displayName: "T. Castagne",    position: "def", fantasyPrice: 7,  shirtNumber: 2,  age: 29 },
    { displayName: "A. Theate",      position: "def", fantasyPrice: 9,  shirtNumber: 15, age: 24 },
    { displayName: "Z. Debast",      position: "def", fantasyPrice: 9,  shirtNumber: 3,  age: 21 },
    { displayName: "T. Alderweireld",position: "def", fantasyPrice: 4,  shirtNumber: 4,  age: 36 },
    { displayName: "J. Vertonghen",  position: "def", fantasyPrice: 4,  shirtNumber: 5,  age: 37 },
    { displayName: "K. De Bruyne",   position: "mid", fantasyPrice: 22, shirtNumber: 7,  age: 33 },
    { displayName: "Y. Tielemans",   position: "mid", fantasyPrice: 11, shirtNumber: 8,  age: 28 },
    { displayName: "L. Trossard",    position: "mid", fantasyPrice: 11, shirtNumber: 11, age: 30 },
    { displayName: "T. Hazard",      position: "mid", fantasyPrice: 7,  shirtNumber: 10, age: 34 },
    { displayName: "R. Lukaku",      position: "fwd", fantasyPrice: 13, shirtNumber: 9,  age: 31 },
    { displayName: "L. Openda",      position: "fwd", fantasyPrice: 13, shirtNumber: 17, age: 24 },
    { displayName: "D. Mertens",     position: "fwd", fantasyPrice: 5,  shirtNumber: 14, age: 37 },
    { displayName: "J. Doku",        position: "fwd", fantasyPrice: 13, shirtNumber: 11, age: 22 },
  ],
  sui: [
    { displayName: "Y. Sommer",      position: "gk",  fantasyPrice: 9,  shirtNumber: 1,  age: 36 },
    { displayName: "G. Kobel",       position: "gk",  fantasyPrice: 11, shirtNumber: 12, age: 27 },
    { displayName: "M. Akanji",      position: "def", fantasyPrice: 11, shirtNumber: 5,  age: 29 },
    { displayName: "N. Elvedi",      position: "def", fantasyPrice: 9,  shirtNumber: 3,  age: 28 },
    { displayName: "R. Rodríguez",   position: "def", fantasyPrice: 5,  shirtNumber: 13, age: 32 },
    { displayName: "S. Widmer",      position: "def", fantasyPrice: 6,  shirtNumber: 2,  age: 30 },
    { displayName: "F. Schär",       position: "def", fantasyPrice: 6,  shirtNumber: 20, age: 32 },
    { displayName: "G. Xhaka",       position: "mid", fantasyPrice: 9,  shirtNumber: 10, age: 32 },
    { displayName: "R. Freuler",     position: "mid", fantasyPrice: 7,  shirtNumber: 8,  age: 32 },
    { displayName: "X. Shaqiri",     position: "mid", fantasyPrice: 6,  shirtNumber: 23, age: 33 },
    { displayName: "R. Vargas",      position: "mid", fantasyPrice: 9,  shirtNumber: 14, age: 26 },
    { displayName: "B. Embolo",      position: "fwd", fantasyPrice: 9,  shirtNumber: 7,  age: 28 },
    { displayName: "N. Okafor",      position: "fwd", fantasyPrice: 11, shirtNumber: 11, age: 25 },
    { displayName: "H. Seferović",   position: "fwd", fantasyPrice: 5,  shirtNumber: 9,  age: 33 },
    { displayName: "Z. Amdouni",     position: "fwd", fantasyPrice: 7,  shirtNumber: 22, age: 24 },
  ],
  aus: [
    { displayName: "M. Ryan",        position: "gk",  fantasyPrice: 6,  shirtNumber: 1,  age: 33 },
    { displayName: "D. Vukovic",     position: "gk",  fantasyPrice: 4,  shirtNumber: 12, age: 39 },
    { displayName: "H. Souttar",     position: "def", fantasyPrice: 7,  shirtNumber: 6,  age: 26 },
    { displayName: "B. Wright",      position: "def", fantasyPrice: 4,  shirtNumber: 5,  age: 34 },
    { displayName: "A. Behich",      position: "def", fantasyPrice: 5,  shirtNumber: 3,  age: 33 },
    { displayName: "N. Atkinson",    position: "def", fantasyPrice: 5,  shirtNumber: 2,  age: 24 },
    { displayName: "J. King",        position: "def", fantasyPrice: 5,  shirtNumber: 16, age: 25 },
    { displayName: "M. Leckie",      position: "mid", fantasyPrice: 7,  shirtNumber: 7,  age: 34 },
    { displayName: "A. Mooy",        position: "mid", fantasyPrice: 6,  shirtNumber: 13, age: 34 },
    { displayName: "A. Hrustic",     position: "mid", fantasyPrice: 6,  shirtNumber: 8,  age: 28 },
    { displayName: "C. Rowles",      position: "mid", fantasyPrice: 5,  shirtNumber: 14, age: 24 },
    { displayName: "M. Duke",        position: "fwd", fantasyPrice: 5,  shirtNumber: 9,  age: 33 },
    { displayName: "J. Maclaren",    position: "fwd", fantasyPrice: 5,  shirtNumber: 17, age: 31 },
    { displayName: "M. Boyle",       position: "fwd", fantasyPrice: 5,  shirtNumber: 11, age: 32 },
    { displayName: "K. Nisbet",      position: "fwd", fantasyPrice: 5,  shirtNumber: 20, age: 27 },
  ],
  iri: [
    { displayName: "A. Beiranvand",  position: "gk",  fantasyPrice: 6,  shirtNumber: 1,  age: 32 },
    { displayName: "A. Abedzadeh",   position: "gk",  fantasyPrice: 4,  shirtNumber: 12, age: 31 },
    { displayName: "M. Hosseini",    position: "def", fantasyPrice: 5,  shirtNumber: 5,  age: 28 },
    { displayName: "M. Mohammadi",   position: "def", fantasyPrice: 4,  shirtNumber: 3,  age: 31 },
    { displayName: "M. Mohebi",      position: "def", fantasyPrice: 4,  shirtNumber: 15, age: 27 },
    { displayName: "S. Khalilzadeh", position: "def", fantasyPrice: 4,  shirtNumber: 19, age: 33 },
    { displayName: "R. Rezaeian",    position: "def", fantasyPrice: 4,  shirtNumber: 2,  age: 33 },
    { displayName: "A. Gholizadeh",  position: "mid", fantasyPrice: 6,  shirtNumber: 11, age: 28 },
    { displayName: "S. Ghoddos",     position: "mid", fantasyPrice: 6,  shirtNumber: 10, age: 30 },
    { displayName: "M. Torabi",      position: "mid", fantasyPrice: 5,  shirtNumber: 14, age: 32 },
    { displayName: "A. Nourollahi",  position: "mid", fantasyPrice: 4,  shirtNumber: 6,  age: 28 },
    { displayName: "M. Taremi",      position: "fwd", fantasyPrice: 11, shirtNumber: 9,  age: 32 },
    { displayName: "S. Azmoun",      position: "fwd", fantasyPrice: 9,  shirtNumber: 7,  age: 30 },
    { displayName: "K. Ansarifard",  position: "fwd", fantasyPrice: 4,  shirtNumber: 19, age: 33 },
    { displayName: "A. Hajsafi",     position: "fwd", fantasyPrice: 4,  shirtNumber: 22, age: 34 },
  ],
  ksa: [
    { displayName: "M. Al-Owais",    position: "gk",  fantasyPrice: 6,  shirtNumber: 21, age: 34 },
    { displayName: "Y. Al-Mosailem", position: "gk",  fantasyPrice: 4,  shirtNumber: 1,  age: 29 },
    { displayName: "A. Al-Bulaihi",  position: "def", fantasyPrice: 4,  shirtNumber: 13, age: 33 },
    { displayName: "A. Al-Amri",     position: "def", fantasyPrice: 5,  shirtNumber: 5,  age: 27 },
    { displayName: "H. Al-Tambakti", position: "def", fantasyPrice: 5,  shirtNumber: 6,  age: 27 },
    { displayName: "S. Abdulhamid",  position: "def", fantasyPrice: 7,  shirtNumber: 2,  age: 25 },
    { displayName: "M. Al-Burayk",   position: "def", fantasyPrice: 4,  shirtNumber: 3,  age: 31 },
    { displayName: "S. Al-Faraj",    position: "mid", fantasyPrice: 5,  shirtNumber: 17, age: 34 },
    { displayName: "M. Kanno",       position: "mid", fantasyPrice: 6,  shirtNumber: 8,  age: 28 },
    { displayName: "F. Al-Buraikan", position: "mid", fantasyPrice: 7,  shirtNumber: 11, age: 23 },
    { displayName: "A. Al-Hamdan",   position: "mid", fantasyPrice: 6,  shirtNumber: 14, age: 24 },
    { displayName: "S. Al-Dawsari",  position: "fwd", fantasyPrice: 9,  shirtNumber: 10, age: 32 },
    { displayName: "H. Asiri",       position: "fwd", fantasyPrice: 4,  shirtNumber: 9,  age: 28 },
    { displayName: "S. Al-Najei",    position: "fwd", fantasyPrice: 4,  shirtNumber: 19, age: 28 },
    { displayName: "N. Al-Dawsari",  position: "fwd", fantasyPrice: 5,  shirtNumber: 7,  age: 25 },
  ],
  ecu: [
    { displayName: "A. Domínguez",   position: "gk",  fantasyPrice: 4,  shirtNumber: 1,  age: 33 },
    { displayName: "H. Galíndez",    position: "gk",  fantasyPrice: 4,  shirtNumber: 12, age: 35 },
    { displayName: "P. Hincapié",    position: "def", fantasyPrice: 13, shirtNumber: 3,  age: 23 },
    { displayName: "F. Torres",      position: "def", fantasyPrice: 9,  shirtNumber: 5,  age: 27 },
    { displayName: "D. Palacios",    position: "def", fantasyPrice: 6,  shirtNumber: 15, age: 24 },
    { displayName: "Á. Preciado",    position: "def", fantasyPrice: 7,  shirtNumber: 22, age: 24 },
    { displayName: "J. Méndez",      position: "def", fantasyPrice: 5,  shirtNumber: 7,  age: 23 },
    { displayName: "C. Gruezo",      position: "mid", fantasyPrice: 5,  shirtNumber: 10, age: 28 },
    { displayName: "J. Sarmiento",   position: "mid", fantasyPrice: 7,  shirtNumber: 11, age: 23 },
    { displayName: "G. Plata",       position: "mid", fantasyPrice: 7,  shirtNumber: 17, age: 24 },
    { displayName: "A. Franco",      position: "mid", fantasyPrice: 6,  shirtNumber: 8,  age: 25 },
    { displayName: "E. Valencia",    position: "fwd", fantasyPrice: 7,  shirtNumber: 13, age: 35 },
    { displayName: "M. Estrada",     position: "fwd", fantasyPrice: 6,  shirtNumber: 9,  age: 27 },
    { displayName: "D. Reasco",      position: "fwd", fantasyPrice: 6,  shirtNumber: 18, age: 24 },
    { displayName: "K. Rodríguez",   position: "fwd", fantasyPrice: 6,  shirtNumber: 16, age: 22 },
  ],
  gha: [
    { displayName: "L. Ati-Zigi",    position: "gk",  fantasyPrice: 6,  shirtNumber: 16, age: 27 },
    { displayName: "I. Danlad",      position: "gk",  fantasyPrice: 3,  shirtNumber: 1,  age: 22 },
    { displayName: "A. Djiku",       position: "def", fantasyPrice: 6,  shirtNumber: 2,  age: 30 },
    { displayName: "D. Amartey",     position: "def", fantasyPrice: 6,  shirtNumber: 5,  age: 30 },
    { displayName: "A. Baba",        position: "def", fantasyPrice: 6,  shirtNumber: 3,  age: 30 },
    { displayName: "G. Mensah",      position: "def", fantasyPrice: 5,  shirtNumber: 17, age: 26 },
    { displayName: "B. Anang",       position: "def", fantasyPrice: 4,  shirtNumber: 19, age: 24 },
    { displayName: "T. Partey",      position: "mid", fantasyPrice: 11, shirtNumber: 5,  age: 31 },
    { displayName: "M. Kudus",       position: "mid", fantasyPrice: 13, shirtNumber: 10, age: 24 },
    { displayName: "I. Baba",        position: "mid", fantasyPrice: 5,  shirtNumber: 15, age: 28 },
    { displayName: "O. Bukari",      position: "mid", fantasyPrice: 6,  shirtNumber: 11, age: 25 },
    { displayName: "J. Ayew",        position: "fwd", fantasyPrice: 6,  shirtNumber: 9,  age: 33 },
    { displayName: "A. Ayew",        position: "fwd", fantasyPrice: 5,  shirtNumber: 7,  age: 34 },
    { displayName: "A. Semenyo",     position: "fwd", fantasyPrice: 9,  shirtNumber: 14, age: 25 },
    { displayName: "I. Sulemana",    position: "fwd", fantasyPrice: 7,  shirtNumber: 8,  age: 22 },
  ],
  nga: [
    { displayName: "F. Uzoho",       position: "gk",  fantasyPrice: 6,  shirtNumber: 1,  age: 26 },
    { displayName: "S. Nwabali",     position: "gk",  fantasyPrice: 5,  shirtNumber: 23, age: 27 },
    { displayName: "W. Troost-Ekong",position: "def", fantasyPrice: 6,  shirtNumber: 5,  age: 31 },
    { displayName: "L. Balogun",     position: "def", fantasyPrice: 5,  shirtNumber: 4,  age: 35 },
    { displayName: "C. Bassey",      position: "def", fantasyPrice: 7,  shirtNumber: 3,  age: 25 },
    { displayName: "Z. Sanusi",      position: "def", fantasyPrice: 6,  shirtNumber: 15, age: 26 },
    { displayName: "B. Osayi-Samuel",position: "def", fantasyPrice: 6,  shirtNumber: 2,  age: 27 },
    { displayName: "A. Iwobi",       position: "mid", fantasyPrice: 9,  shirtNumber: 10, age: 29 },
    { displayName: "F. Onyeka",      position: "mid", fantasyPrice: 6,  shirtNumber: 8,  age: 26 },
    { displayName: "O. Ndidi",       position: "mid", fantasyPrice: 9,  shirtNumber: 4,  age: 28 },
    { displayName: "S. Chukwueze",   position: "mid", fantasyPrice: 11, shirtNumber: 7,  age: 26 },
    { displayName: "V. Osimhen",     position: "fwd", fantasyPrice: 22, shirtNumber: 9,  age: 26 },
    { displayName: "T. Awoniyi",     position: "fwd", fantasyPrice: 9,  shirtNumber: 11, age: 27 },
    { displayName: "K. Iheanacho",   position: "fwd", fantasyPrice: 6,  shirtNumber: 14, age: 29 },
    { displayName: "A. Lookman",     position: "fwd", fantasyPrice: 15, shirtNumber: 17, age: 27 },
  ],
  cmr: [
    { displayName: "A. Onana",       position: "gk",  fantasyPrice: 17, shirtNumber: 1,  age: 29 },
    { displayName: "D. Epassy",      position: "gk",  fantasyPrice: 4,  shirtNumber: 12, age: 30 },
    { displayName: "N. Nkoulou",     position: "def", fantasyPrice: 4,  shirtNumber: 5,  age: 34 },
    { displayName: "M. Ngadeu",      position: "def", fantasyPrice: 4,  shirtNumber: 3,  age: 33 },
    { displayName: "C. Fai",         position: "def", fantasyPrice: 4,  shirtNumber: 2,  age: 32 },
    { displayName: "N. Tolo",        position: "def", fantasyPrice: 5,  shirtNumber: 15, age: 28 },
    { displayName: "J. Castelletto", position: "def", fantasyPrice: 6,  shirtNumber: 21, age: 29 },
    { displayName: "A. Anguissa",    position: "mid", fantasyPrice: 17, shirtNumber: 8,  age: 29 },
    { displayName: "S. Gouet",       position: "mid", fantasyPrice: 7,  shirtNumber: 17, age: 27 },
    { displayName: "M. Hongla",      position: "mid", fantasyPrice: 6,  shirtNumber: 18, age: 26 },
    { displayName: "J. Mbappe",      position: "mid", fantasyPrice: 5,  shirtNumber: 11, age: 30 },
    { displayName: "V. Aboubakar",   position: "fwd", fantasyPrice: 7,  shirtNumber: 9,  age: 33 },
    { displayName: "K. Toko Ekambi", position: "fwd", fantasyPrice: 7,  shirtNumber: 7,  age: 32 },
    { displayName: "C. Choupo-Moting",position:"fwd", fantasyPrice: 6,  shirtNumber: 14, age: 36 },
    { displayName: "B. Moumi",       position: "fwd", fantasyPrice: 5,  shirtNumber: 10, age: 23 },
  ],
  egy: [
    { displayName: "M. El-Shenawy", position: "gk",  fantasyPrice: 6,  shirtNumber: 1,  age: 37 },
    { displayName: "A. El-Shenawy", position: "gk",  fantasyPrice: 4,  shirtNumber: 12, age: 34 },
    { displayName: "A. Hegazi",     position: "def", fantasyPrice: 4,  shirtNumber: 5,  age: 34 },
    { displayName: "K. Hafez",      position: "def", fantasyPrice: 4,  shirtNumber: 4,  age: 31 },
    { displayName: "M. Hany",       position: "def", fantasyPrice: 5,  shirtNumber: 2,  age: 27 },
    { displayName: "M. Abdel-Shafi",position: "def", fantasyPrice: 5,  shirtNumber: 3,  age: 29 },
    { displayName: "A. Hamdi",      position: "def", fantasyPrice: 5,  shirtNumber: 13, age: 29 },
    { displayName: "M. Salah",      position: "mid", fantasyPrice: 22, shirtNumber: 10, age: 33 },
    { displayName: "T. Hamed",      position: "mid", fantasyPrice: 5,  shirtNumber: 8,  age: 30 },
    { displayName: "O. Marmoush",   position: "mid", fantasyPrice: 17, shirtNumber: 7,  age: 26 },
    { displayName: "M. Trezeguet",  position: "mid", fantasyPrice: 6,  shirtNumber: 11, age: 30 },
    { displayName: "M. Mohamed",    position: "fwd", fantasyPrice: 9,  shirtNumber: 9,  age: 27 },
    { displayName: "R. Hamdi",      position: "fwd", fantasyPrice: 6,  shirtNumber: 19, age: 29 },
    { displayName: "K. Hamdi",      position: "fwd", fantasyPrice: 5,  shirtNumber: 20, age: 30 },
    { displayName: "Z. El-Gamal",   position: "fwd", fantasyPrice: 5,  shirtNumber: 17, age: 25 },
  ],
  tur: [
    { displayName: "M. Günok",      position: "gk",  fantasyPrice: 6,  shirtNumber: 12, age: 34 },
    { displayName: "U. Çakır",      position: "gk",  fantasyPrice: 7,  shirtNumber: 1,  age: 33 },
    { displayName: "M. Demiral",    position: "def", fantasyPrice: 9,  shirtNumber: 3,  age: 26 },
    { displayName: "Ç. Söyüncü",    position: "def", fantasyPrice: 9,  shirtNumber: 4,  age: 29 },
    { displayName: "S. Akaydin",    position: "def", fantasyPrice: 6,  shirtNumber: 5,  age: 28 },
    { displayName: "Z. Çelik",      position: "def", fantasyPrice: 7,  shirtNumber: 2,  age: 27 },
    { displayName: "F. Kadıoğlu",   position: "def", fantasyPrice: 9,  shirtNumber: 15, age: 25 },
    { displayName: "H. Çalhanoğlu", position: "mid", fantasyPrice: 13, shirtNumber: 10, age: 33 },
    { displayName: "A. Güler",      position: "mid", fantasyPrice: 20, shirtNumber: 11, age: 20 },
    { displayName: "K. Yıldız",     position: "mid", fantasyPrice: 11, shirtNumber: 17, age: 19 },
    { displayName: "B. Yılmaz",     position: "mid", fantasyPrice: 9,  shirtNumber: 7,  age: 25 },
    { displayName: "B. Yılmaz",     position: "fwd", fantasyPrice: 4,  shirtNumber: 9,  age: 39 },
    { displayName: "C. Tosun",      position: "fwd", fantasyPrice: 4,  shirtNumber: 14, age: 33 },
    { displayName: "S. Dursun",     position: "fwd", fantasyPrice: 5,  shirtNumber: 19, age: 34 },
    { displayName: "İ. Yüksek",     position: "fwd", fantasyPrice: 7,  shirtNumber: 8,  age: 24 },
  ],
  pol: [
    { displayName: "W. Szczęsny",   position: "gk",  fantasyPrice: 9,  shirtNumber: 1,  age: 35 },
    { displayName: "Ł. Fabiański",  position: "gk",  fantasyPrice: 4,  shirtNumber: 22, age: 39 },
    { displayName: "J. Bednarek",   position: "def", fantasyPrice: 7,  shirtNumber: 5,  age: 29 },
    { displayName: "B. Bereszyński",position: "def", fantasyPrice: 5,  shirtNumber: 2,  age: 33 },
    { displayName: "A. Jędrzejczyk",position: "def", fantasyPrice: 4,  shirtNumber: 15, age: 37 },
    { displayName: "J. Kiwior",     position: "def", fantasyPrice: 9,  shirtNumber: 5,  age: 25 },
    { displayName: "P. Frankowski", position: "def", fantasyPrice: 6,  shirtNumber: 18, age: 30 },
    { displayName: "P. Zieliński",  position: "mid", fantasyPrice: 13, shirtNumber: 10, age: 30 },
    { displayName: "K. Piątek",     position: "mid", fantasyPrice: 6,  shirtNumber: 7,  age: 29 },
    { displayName: "S. Żurkowski",  position: "mid", fantasyPrice: 6,  shirtNumber: 14, age: 27 },
    { displayName: "J. Moder",      position: "mid", fantasyPrice: 5,  shirtNumber: 13, age: 26 },
    { displayName: "R. Lewandowski",position: "fwd", fantasyPrice: 20, shirtNumber: 9,  age: 37 },
    { displayName: "A. Milik",      position: "fwd", fantasyPrice: 9,  shirtNumber: 11, age: 31 },
    { displayName: "K. Grosicki",   position: "fwd", fantasyPrice: 5,  shirtNumber: 8,  age: 36 },
    { displayName: "K. Świderski",  position: "fwd", fantasyPrice: 7,  shirtNumber: 21, age: 28 },
  ],
  aut: [
    { displayName: "P. Pentz",      position: "gk",  fantasyPrice: 5,  shirtNumber: 1,  age: 27 },
    { displayName: "A. Schlager",   position: "gk",  fantasyPrice: 5,  shirtNumber: 12, age: 30 },
    { displayName: "A. Dragović",   position: "def", fantasyPrice: 4,  shirtNumber: 6,  age: 33 },
    { displayName: "P. Lienhart",   position: "def", fantasyPrice: 6,  shirtNumber: 5,  age: 28 },
    { displayName: "M. Wöber",      position: "def", fantasyPrice: 9,  shirtNumber: 4,  age: 26 },
    { displayName: "S. Posch",      position: "def", fantasyPrice: 6,  shirtNumber: 2,  age: 27 },
    { displayName: "P. Mwene",      position: "def", fantasyPrice: 5,  shirtNumber: 19, age: 30 },
    { displayName: "D. Alaba",      position: "mid", fantasyPrice: 11, shirtNumber: 8,  age: 33 },
    { displayName: "M. Sabitzer",   position: "mid", fantasyPrice: 9,  shirtNumber: 7,  age: 31 },
    { displayName: "F. Grillitsch", position: "mid", fantasyPrice: 6,  shirtNumber: 14, age: 29 },
    { displayName: "C. Baumgartner",position: "mid", fantasyPrice: 9,  shirtNumber: 17, age: 25 },
    { displayName: "M. Arnautović", position: "fwd", fantasyPrice: 6,  shirtNumber: 9,  age: 36 },
    { displayName: "M. Gregoritsch",position: "fwd", fantasyPrice: 6,  shirtNumber: 11, age: 30 },
    { displayName: "S. Kalajdzic",  position: "fwd", fantasyPrice: 7,  shirtNumber: 21, age: 27 },
    { displayName: "P. Wimmer",     position: "fwd", fantasyPrice: 6,  shirtNumber: 22, age: 23 },
  ],
  srb: [
    { displayName: "V. Milinković-Savić",position:"gk", fantasyPrice: 9, shirtNumber: 12, age: 27 },
    { displayName: "P. Rajković",   position: "gk",  fantasyPrice: 6,  shirtNumber: 1,  age: 30 },
    { displayName: "N. Milenković", position: "def", fantasyPrice: 11, shirtNumber: 4,  age: 27 },
    { displayName: "S. Pavlović",   position: "def", fantasyPrice: 11, shirtNumber: 5,  age: 23 },
    { displayName: "F. Kostić",     position: "def", fantasyPrice: 9,  shirtNumber: 11, age: 32 },
    { displayName: "S. Mitrović",   position: "def", fantasyPrice: 4,  shirtNumber: 3,  age: 30 },
    { displayName: "S. Babić",      position: "def", fantasyPrice: 5,  shirtNumber: 14, age: 27 },
    { displayName: "D. Tadić",      position: "mid", fantasyPrice: 7,  shirtNumber: 10, age: 36 },
    { displayName: "S. Milinković-Savić",position:"mid",fantasyPrice:17,shirtNumber:8, age:29 },
    { displayName: "N. Gudelj",     position: "mid", fantasyPrice: 6,  shirtNumber: 13, age: 33 },
    { displayName: "S. Lukić",      position: "mid", fantasyPrice: 6,  shirtNumber: 15, age: 28 },
    { displayName: "D. Vlahović",   position: "fwd", fantasyPrice: 20, shirtNumber: 9,  age: 25 },
    { displayName: "A. Mitrović",   position: "fwd", fantasyPrice: 17, shirtNumber: 11, age: 30 },
    { displayName: "L. Jović",      position: "fwd", fantasyPrice: 7,  shirtNumber: 7,  age: 27 },
    { displayName: "A. Živković",   position: "fwd", fantasyPrice: 6,  shirtNumber: 19, age: 29 },
  ],
};

export async function seedWC2026(): Promise<void> {
  const db = admin.firestore();
  console.log("Seeding WC 2026 teams and players...");
  const batch = db.batch();
  let count = 0;

  for (const team of TEAMS) {
    const teamRef = db.collection("teams").doc(team.id);
    batch.set(teamRef, {
      ...team,
      tournamentId: TOURNAMENT_ID,
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    });

    const players = PLAYERS[team.id] ?? [];
    for (const p of players) {
      const playerId = `${team.id}_${p.displayName.toLowerCase().replace(/[^a-z0-9]/g, "_")}`;
      const playerRef = db.collection("players").doc(playerId);
      batch.set(playerRef, {
        displayName: p.displayName,
        position: p.position,
        fantasyPrice: p.fantasyPrice,
        shirtNumber: p.shirtNumber ?? null,
        age: p.age ?? null,
        teamId: team.id,
        teamName: team.name,
        countryCode: team.countryCode,
        tournamentId: TOURNAMENT_ID,
        status: "active",
        ownershipPct: 0,
        statsSummary: { appearances: 0, goals: 0, assists: 0, yellowCards: 0, redCards: 0, totalFantasyPoints: 0 },
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      });
      count++;
    }
  }

  await batch.commit();
  console.log(`✅ Seeded ${TEAMS.length} teams and ${count} players.`);
}
